"""initial_schema

Revision ID: 32839c6e60c9
Revises: 
Create Date: 2026-06-22 10:47:20.007902

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '32839c6e60c9'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('residential_complexes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('district', sa.String(length=255), server_default='', nullable=False),
    sa.Column('city', sa.String(length=100), server_default='Astana', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_residential_complexes_name'), 'residential_complexes', ['name'], unique=True)
    op.create_table('apartments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('complex_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('price_per_sqm', sa.Float(), nullable=False),
    sa.Column('district', sa.String(length=255), server_default='', nullable=False),
    sa.Column('address', sa.String(length=512), server_default='', nullable=False),
    sa.Column('rooms', sa.Integer(), nullable=False),
    sa.Column('total_area', sa.Float(), nullable=False),
    sa.Column('living_area', sa.Float(), nullable=True),
    sa.Column('kitchen_area', sa.Float(), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('total_floors', sa.Integer(), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('house_type', sa.String(length=100), nullable=True),
    sa.Column('ceiling_height', sa.Float(), nullable=True),
    sa.Column('condition', sa.String(length=100), nullable=True),
    sa.Column('balcony', sa.String(length=100), nullable=True),
    sa.Column('bathroom', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('photos', sa.JSON(), nullable=True),
    sa.Column('seller_type', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['complex_id'], ['residential_complexes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index('ix_apartments_complex_id', 'apartments', ['complex_id'], unique=False)
    op.create_index('ix_apartments_is_active', 'apartments', ['is_active'], unique=False)
    op.create_table('apartment_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apartment_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('price_per_sqm', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apartment_prices_apartment_id'), 'apartment_prices', ['apartment_id'], unique=False)
    op.create_table('apartment_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apartment_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'price_changed', name='apartment_status'), nullable=False),
    sa.Column('old_price', sa.Integer(), nullable=True),
    sa.Column('new_price', sa.Integer(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apartment_status_history_apartment_id'), 'apartment_status_history', ['apartment_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apartment_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_sent', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_apartment_id'), 'notifications', ['apartment_id'], unique=False)
    op.create_table('sellers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apartment_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('seller_type', sa.Enum('owner', 'agent', 'agency', name='seller_type'), nullable=True),
    sa.Column('owner_probability', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sellers_apartment_id'), 'sellers', ['apartment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sellers_apartment_id'), table_name='sellers')
    op.drop_table('sellers')
    op.drop_index(op.f('ix_notifications_apartment_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_apartment_status_history_apartment_id'), table_name='apartment_status_history')
    op.drop_table('apartment_status_history')
    op.drop_index(op.f('ix_apartment_prices_apartment_id'), table_name='apartment_prices')
    op.drop_table('apartment_prices')
    op.drop_index('ix_apartments_is_active', table_name='apartments')
    op.drop_index('ix_apartments_complex_id', table_name='apartments')
    op.drop_table('apartments')
    op.drop_index(op.f('ix_residential_complexes_name'), table_name='residential_complexes')
    op.drop_table('residential_complexes')
    op.execute("DROP TYPE IF EXISTS apartment_status")
    op.execute("DROP TYPE IF EXISTS seller_type")
    # ### end Alembic commands ###
