"""add_analytics

Revision ID: 556673d599e2
Revises: 5c0eebe028d0
Create Date: 2026-06-22 13:57:02.101585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '556673d599e2'
down_revision: Union[str, Sequence[str], None] = '5c0eebe028d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complex_id', sa.Integer(), nullable=True),
    sa.Column('district', sa.String(length=255), nullable=True),
    sa.Column('rooms', sa.Integer(), nullable=True),
    sa.Column('median_price', sa.Integer(), nullable=False),
    sa.Column('avg_price', sa.Integer(), nullable=False),
    sa.Column('median_price_per_sqm', sa.Integer(), nullable=False),
    sa.Column('avg_price_per_sqm', sa.Float(), nullable=False),
    sa.Column('active_count', sa.Integer(), nullable=False),
    sa.Column('sold_last_30d', sa.Integer(), server_default='0', nullable=False),
    sa.Column('avg_days_on_market', sa.Float(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['complex_id'], ['residential_complexes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_analytics_complex_id_calculated_at', 'analytics', ['complex_id', 'calculated_at'], unique=False)
    op.create_index('ix_analytics_district_calculated_at', 'analytics', ['district', 'calculated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_analytics_district_calculated_at', table_name='analytics')
    op.drop_index('ix_analytics_complex_id_calculated_at', table_name='analytics')
    op.drop_table('analytics')
    # ### end Alembic commands ###
