"""add_search_configs

Revision ID: 5c0eebe028d0
Revises: 32839c6e60c9
Create Date: 2026-06-22 11:24:32.275431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c0eebe028d0'
down_revision: Union[str, Sequence[str], None] = '32839c6e60c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('city', sa.String(length=100), server_default='astana', nullable=False),
    sa.Column('rooms', sa.Integer(), nullable=True),
    sa.Column('price_from', sa.Integer(), nullable=True),
    sa.Column('price_to', sa.Integer(), nullable=True),
    sa.Column('floor_from', sa.Integer(), nullable=True),
    sa.Column('floor_to', sa.Integer(), nullable=True),
    sa.Column('building_floors_from', sa.Integer(), nullable=True),
    sa.Column('building_floors_to', sa.Integer(), nullable=True),
    sa.Column('year_from', sa.Integer(), nullable=True),
    sa.Column('year_to', sa.Integer(), nullable=True),
    sa.Column('area_from', sa.Float(), nullable=True),
    sa.Column('area_to', sa.Float(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('complex_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('search_configs')
    # ### end Alembic commands ###
